### ISSUE TITLE
Process the time series: Permission denied creating output tif 

### ISSUE THREAD

**Issue by jdilger** [smfm-project/deforest#3]
Related to #2 I cloned this repository via the command line and was able to get the first cell to run. However, when trying to run the example process time-series I get another permissions error when trying to write the output tiff.
```
Doing 2021-02-22
Doing 2021-03-10
Outputting maps
ERROR 4: Attempt to create new tiff file `/home/jdilger/shared/notebooks/deforest/sepal/sampleOutput_confirmed.tif' failed: Permission denied
Traceback (most recent call last):
  File "/home/jdilger/deforest/sepal/change.py", line 190, in <module>
    main(args.source_dir, deforestation_threshold = args.threshold, block_weight = args.block_weight, scale_factor = args.scale_factor, date_range = args.date_range, output_dir = args.output_dir, output_name = args.output_name, verbose = args.verbose)
  File "/home/jdilger/deforest/sepal/change.py", line 160, in main
    deforest.change.outputImage(deforestation_confirmed, stack_file, '%s/%s_%s.tif'%(output_dir, output_name, 'confirmed'))
  File "/usr/local/lib/python3.6/dist-packages/deforest-0.1-py3.6.egg/deforest/change.py", line 278, in outputImage
    ds.SetGeoTransform(data_ds.GetGeoTransform())
AttributeError: 'NoneType' object has no attribute 'SetGeoTransform'
ls: cannot access 'sampleOutput*': No such file or directory
```

to reproduce:
1. In terminal 
``` git clone https://github.com/smfm-project/deforest ```
2. open deforest notebook in SEPAL
3. run cell 2

**Comment by samuelbowers** [comment]
Thanks, workaround in place by specifying output to the user's home directory. Tidier fix to follow.
